---
engines:
  duplication:
    config:
      languages:
        - php
    enabled: true
  engines:
    phpcodesniffer:
      enabled: true
    phpmd:
      enabled: true
exclude_paths:
  - vendor/**/*
ratings:
  paths:
    - "**.php"
