---
engines:
  brakeman:
    enabled: true
  csslint:
    enabled: true
  duplication:
    config:
      languages:
        - php
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
exclude_paths:
  - vendor/**/*
ratings:
  paths:
    - "**.php"
